### ISSUE TITLE
Ability of capturing full screen instead of current view

### ISSUE THREAD

**Issue by ducan-ne** [web-infra-dev/midscene#143]
Playwright supports capturing screenshot full page and I think it would be nice to support in Midscene https://playwright.dev/docs/screenshots#full-page-screenshots

Use cases: aiAction is fine, but for aiQuery (or aiAssert/aiWaitFor), the current view is not always fit for all items, but keep scrolling and run aiExtract seems weird to me

Trade-off:
	•	AI costs will increase significantly.
	•	The number of elements sent to the LLM will grow with the DOM size, but I believe we only need to send DOM in the view like as is.

**Comment by zhoushaw** [comment]
@ducan-ne  Thank you for your question. We considered this issue thoroughly earlier and found that extracting the entire page instead of just the visible area could introduce a few additional concerns:

1. The number of tokens sent would increase significantly, which would slow down the AI’s response and might cause unnecessary token usage.
2. Extracting non-visible areas could lead to unexpected behavior, as it would allow users to manipulate content they haven't yet viewed, which can be confusing.

**Comment by zhoushaw** [comment]
@ducan-ne If your goal is to send more content from a page to the AI for information extraction, you can try adjusting the page's height to your desired size. This way, more of the required information can be included and sent.

**Comment by zhoushaw** [comment]
@ducan-ne GPT-4 does not recommend passing images larger than 1792x1024, as it may lead to poor comprehension by the LLM. I don’t quite understand why you would need the entire page. Isn’t your scenario for E2E testing? If it is E2E testing, the testing steps should follow human actions to simulate behavior.
