### ISSUE TITLE
[Bug] MIDSCENE_USE_ANTHROPIC_SDK=1 Environment Variable Not Working in Chrome Extension Configuration

### ISSUE THREAD

**Issue by sincerity711** [web-infra-dev/midscene#217]
**Where are you using Midscene.js**  
Chrome extension  

**The version of Midscene.js**  
Chrome extension: December 16, 2024

**The model name and endpoint (if could be public)**  
claude-3-5-sonnet-20240620

**The error message**  
The `MIDSCENE_USE_ANTHROPIC_SDK=1` environment variable is not recognized or effective when configured in the Chrome extension settings.  

**Additional Notes**  
When using YAML configuration and Puppeteer, the environment variable works as expected. However, it does not take effect when using the Chrome extension. If additional debugging steps are required, please let me know.

**Comment by yuyutaotao** [comment]
Hi, the extension version that supports Anthropic has just been declined by Chrome Extension Store due to permission issues. We are still finding a way to solve this. 😭

You may use the zip package of the extension from the GitHub Action for temporary purposes, which can be found in the 'Artifacts' section of the workflow.https://github.com/web-infra-dev/midscene/actions/runs/12500048856

**Comment by yuyutaotao** [comment]
The latest v0.15 extension has been released in the Chrome Extension store. You can give it a try.
